server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://hjdfvsieftismx:f8e54def4009a334e23da16476bce3740b3438f7fc79d8884cfd71b13d738597@ec2-18-207-95-219.compute-1.amazonaws.com:5432/d98o2a87ntsvm4
    username: hjdfvsieftismx
    password: f8e54def4009a334e23da16476bce3740b3438f7fc79d8884cfd71b13d738597
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
